sudo: required

services:
  - docker

before_install:
  - sudo apt-get clean && sudo apt-get update -y
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - docker --version
  - git clone https://github.com/sstephenson/bats.git

script:
  - docker build --rm=true -t $DOCKER_IMAGE_NAME .

env:
  - DOCKER_IMAGE_NAME=frekele/helicopterizer

